"""my_new_feature

Revision ID: e2452ef12b73
Revises: 40ae859bce90
Create Date: 2023-11-09 10:12:43.186934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2452ef12b73'
down_revision = '40ae859bce90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
